### ISSUE TITLE
Specifying n_jobs = -1  causes un-serialize error

### ISSUE THREAD

**Issue by jkmackie** [aldente0630/gauss_rank_scaler#2]
The code I want to parallelize is below.  I inserted n_jobs = -1 as a GaussRankScaler() argument:

```
scaler = GaussRankScaler(n_jobs=-1)
Xtr_gr = scaler.fit_transform(Xtr)
```

Using ```fit```and then ```transform``` in place of ```fit_transform``` makes no difference.

The error is below.  Let me know if you need additional details.

```

---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Justin\miniconda3\envs\venv\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Users\Justin\miniconda3\envs\venv\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\Justin\miniconda3\envs\venv\lib\site-packages\numpy\core\__init__.py", line 126, in _ufunc_reconstruct
    return getattr(mod, name)
AttributeError: module '__main__' has no attribute 'erfinv'
"""

The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-71-baf71ff3a7db> in <module>
      3 te_idx = Xte.index
      4 scaler = GaussRankScaler(n_jobs=-1)
----> 5 Xtr_gr = scaler.fit_transform(Xtr)
      6 Xte_gr = pd.DataFrame(Xte_gr, index=te_idx, columns=te_cols)  #convert to df to drop NaNs.
      7 

~\miniconda3\envs\venv\lib\site-packages\sklearn\base.py in fit_transform(self, X, y, **fit_params)
    688         if y is None:
    689             # fit method of arity 1 (unsupervised transformation)
--> 690             return self.fit(X, **fit_params).transform(X)
    691         else:
    692             # fit method of arity 2 (supervised transformation)

<ipython-input-51-504bc32fca45> in fit(self, X, y)
     63 
     64         #Iterate through columns.  Do this by transposing the columns in X to rows.
---> 65         self.interp_func_ = Parallel(n_jobs=self.n_jobs)(delayed(self._fit)(x) for x in X.T)
     66         return self
     67 

~\miniconda3\envs\venv\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~\miniconda3\envs\venv\lib\site-packages\joblib\parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~\miniconda3\envs\venv\lib\site-packages\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~\miniconda3\envs\venv\lib\concurrent\futures\_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

~\miniconda3\envs\venv\lib\concurrent\futures\_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

GaussRankScaler() runs fine if n_jobs is left at the default value of None.

**Comment by bits-bytes-nn** [comment]
Unfortunately, I wasn't able to reproduce the problem you mentioned on my computer. Can you give me more details?

**Comment by jkmackie** [comment]
I'll close this issue since I no longer get an error.

A year later, my package manager (now pip 21.3.1 rather than conda) and library versions are different.  This is a reminder that dependency versions must be frozen for reproducibility!
